#!/bin/sh
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
readme_file="$repo_root/README.md"
begin_marker='<!-- BEGIN GENERATED TOC -->'
end_marker='<!-- END GENERATED TOC -->'
tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/research-toc.XXXXXX")
block_file="$tmp_dir/toc-block.md"
tmp_file="$tmp_dir/README.md"

cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT HUP INT TERM

validate_link_path() {
  path=$1
  case $path in
  /* | ../* | */../* | *'//'*) return 1 ;;
  *[!ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._/-]*) return 1 ;;
  *) return 0 ;;
  esac
}

emit_link_list() {
  while IFS= read -r path; do
    [ -n "$path" ] || continue
    if ! validate_link_path "$path"; then
      printf 'error: unsafe path for generated Markdown link: %s\n' "$path" >&2
      exit 1
    fi
    case $path in
    drafts/*/*) name=${path#drafts/} ;;
    *) name=${path##*/} ;;
    esac
    printf -- '- [%s](./%s)\n' "$name" "$path"
  done
}

{
  printf '%s\n' "$begin_marker"
  printf '## Table of Contents\n\n'
  printf 'Generated by `generate-toc.sh`.\n\n'

  printf '### Repository\n\n'
  {
    [ -f "$repo_root/LICENSE.md" ] && printf 'LICENSE.md\n'
  } | sort | emit_link_list
  printf '\n'

  printf '### Published Documents\n\n'
  for file in "$repo_root"/*.html; do
    [ -f "$file" ] || continue
    printf '%s\n' "${file##*/}"
  done | sort | emit_link_list
  printf '\n'

  printf '### Drafts\n\n'
  find "$repo_root/drafts" -type f -name '*.html' -print |
    sed "s|^$repo_root/||" |
    sort |
    emit_link_list
  printf '%s\n' "$end_marker"
} >"$block_file"

if grep -Fq "$begin_marker" "$readme_file"; then
  has_begin=1
else
  has_begin=0
fi

if grep -Fq "$end_marker" "$readme_file"; then
  has_end=1
else
  has_end=0
fi

if [ "$has_begin" -ne "$has_end" ]; then
  printf 'error: README.md has only one generated TOC marker\n' >&2
  exit 1
fi

if [ "$has_begin" -eq 1 ]; then
  awk -v begin="$begin_marker" -v end="$end_marker" -v block="$block_file" '
		$0 == begin {
			while ((getline line < block) > 0) {
				print line
			}
			close(block)
			in_block = 1
			next
		}
		$0 == end {
			in_block = 0
			next
		}
		!in_block {
			print
		}
	' "$readme_file" >"$tmp_file"
else
  {
    cat "$readme_file"
    printf '\n\n'
    cat "$block_file"
  } >"$tmp_file"
fi

mv "$tmp_file" "$readme_file"
