#!/bin/sh
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
toc_file="$repo_root/TOC.md"
tmp_file="$toc_file.tmp.$$"

cleanup() {
	rm -f "$tmp_file"
}
trap cleanup EXIT HUP INT TERM

emit_link_list() {
	while IFS= read -r path; do
		[ -n "$path" ] || continue
		name=${path##*/}
		printf -- '- [%s](%s)\n' "$name" "$path"
	done
}

{
	printf '# Table of Contents\n\n'
	printf 'Generated by `generate-toc.sh`.\n\n'

	printf '## Repository\n\n'
	{
		[ -f "$repo_root/LICENSE.md" ] && printf 'LICENSE.md\n'
		[ -f "$repo_root/README.md" ] && printf 'README.md\n'
	} | sort | emit_link_list
	printf '\n'

	printf '## Published Documents\n\n'
	for file in "$repo_root"/*.html; do
		[ -f "$file" ] || continue
		printf '%s\n' "${file##*/}"
	done | sort | emit_link_list
	printf '\n'

	printf '## Drafts\n\n'
	for file in "$repo_root"/_draft/*.html; do
		[ -f "$file" ] || continue
		printf '_draft/%s\n' "${file##*/}"
	done | sort | emit_link_list
} > "$tmp_file"

mv "$tmp_file" "$toc_file"
trap - EXIT HUP INT TERM
